package rpc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-03-26T16:45:42.340+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://www.example.org/kalkulator/",
	name = "kalkulator",
	wsdlLocation = "WEB-INF/wsdl/kalkulator-rpc.wsdl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Kalkulator {

    @WebMethod(action = "http://www.example.org/kalkulator/mul")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/kalkulator/", partName = "result")
    public int mul(
            @WebParam(partName = "arg1", name = "arg1")
                    int arg1,
            @WebParam(partName = "arg2", name = "arg2")
                    int arg2
    );

//    @WebMethod(action = "http://www.example.org/kalkulator/avg")
//    @WebResult(name = "result", targetNamespace = "http://www.example.org/kalkulator/", partName = "result")
//    public double avg(
//            @WebParam(partName = "args", name = "args")
//                    ManyInts args
//    );

    @WebMethod(action = "http://www.example.org/kalkulator/add")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/kalkulator/", partName = "result")
    public int add(
            @WebParam(partName = "arg1", name = "arg1")
                    int arg1,
            @WebParam(partName = "arg2", name = "arg2")
                    int arg2
    );

    @WebMethod(action = "http://www.example.org/kalkulator/div")
    public void div(
            @WebParam(partName = "arg1", name = "arg1")
                    int arg1,
            @WebParam(partName = "arg2", name = "arg2")
                    int arg2,
            @WebParam(partName = "quotient", mode = WebParam.Mode.OUT, name = "quotient")
                    javax.xml.ws.Holder<Integer> quotient,
            @WebParam(partName = "remainder", mode = WebParam.Mode.OUT, name = "remainder")
                    javax.xml.ws.Holder<Integer> remainder
    );

    @WebMethod(action = "http://www.example.org/kalkulator/sub")
    @WebResult(name = "result", targetNamespace = "http://www.example.org/kalkulator/", partName = "result")
    public int sub(
            @WebParam(partName = "arg1", name = "arg1")
                    int arg1,
            @WebParam(partName = "arg2", name = "arg2")
                    int arg2
    );
}
