
package main.java.client.xmlGenerated;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeatherComparator", targetNamespace = "http://www.example.org/WeatherComparator/", wsdlLocation = "http://localhost:8080/unnamed/WeatherComparator?wsdl")
public class WeatherComparatorService
    extends Service
{

    private final static URL WEATHERCOMPARATOR_WSDL_LOCATION;
    private final static WebServiceException WEATHERCOMPARATOR_EXCEPTION;
    private final static QName WEATHERCOMPARATOR_QNAME = new QName("http://www.example.org/WeatherComparator/", "WeatherComparator");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/unnamed/WeatherComparator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEATHERCOMPARATOR_WSDL_LOCATION = url;
        WEATHERCOMPARATOR_EXCEPTION = e;
    }

    public WeatherComparatorService() {
        super(__getWsdlLocation(), WEATHERCOMPARATOR_QNAME);
    }

    public WeatherComparatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEATHERCOMPARATOR_QNAME, features);
    }

    public WeatherComparatorService(URL wsdlLocation) {
        super(wsdlLocation, WEATHERCOMPARATOR_QNAME);
    }

    public WeatherComparatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEATHERCOMPARATOR_QNAME, features);
    }

    public WeatherComparatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeatherComparatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeatherComparator
     */
    @WebEndpoint(name = "WeatherComparatorSOAP")
    public WeatherComparator getWeatherComparatorSOAP() {
        return super.getPort(new QName("http://www.example.org/WeatherComparator/", "WeatherComparatorSOAP"), WeatherComparator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeatherComparator
     */
    @WebEndpoint(name = "WeatherComparatorSOAP")
    public WeatherComparator getWeatherComparatorSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/WeatherComparator/", "WeatherComparatorSOAP"), WeatherComparator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEATHERCOMPARATOR_EXCEPTION!= null) {
            throw WEATHERCOMPARATOR_EXCEPTION;
        }
        return WEATHERCOMPARATOR_WSDL_LOCATION;
    }

}
