
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherComparator", targetNamespace = "http://www.example.org/WeatherComparator/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeatherComparator {


    /**
     * 
     * @param result
     * @param forecastDays
     */
    @WebMethod(action = "http://www.example.org/WeatherComparator/compareForecast")
    @Action(input = "http://www.example.org/WeatherComparator/compareForecast", output = "http://www.example.org/WeatherComparator/WeatherComparator/compareForecastResponse")
    public void compareForecast(
            @WebParam(name = "forecastDays", partName = "forecastDays")
                    ManyDays forecastDays,
            @WebParam(name = "result", mode = WebParam.Mode.OUT, partName = "result")
                    Holder<WeatherSummary> result);

}
